"""add refresh token to users

Revision ID: 61faa8ee521b
Revises: d0921e7d5abb
Create Date: 2025-02-15 16:26:08.094119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61faa8ee521b'
down_revision: Union[str, None] = 'd0921e7d5abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
