"""Added Feedback Table

Revision ID: 86435f61efdb
Revises: 6c95721b7ce8
Create Date: 2025-03-09 14:34:48.603209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86435f61efdb'
down_revision: Union[str, None] = '6c95721b7ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('interview_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('overall_feedback', sa.Text(), nullable=False),
    sa.Column('strengths', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('improvement_areas', sa.Text(), nullable=False),
    sa.Column('next_steps', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.interview_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_index(op.f('ix_interview_feedback_feedback_id'), 'interview_feedback', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_feedback_feedback_id'), table_name='interview_feedback')
    op.drop_table('interview_feedback')
    # ### end Alembic commands ###
