"""dropped techstack prompt table

Revision ID: e14561fdeb68
Revises: 72abef1c49e2
Create Date: 2025-02-25 15:25:44.266698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e14561fdeb68'
down_revision: Union[str, None] = '72abef1c49e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tech_stack_prompts')
    op.add_column('prompts', sa.Column('tech_stack', sa.String(), nullable=False))
    op.add_column('prompts', sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False))
    op.alter_column('prompts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('prompts', 'category')
    op.drop_column('prompts', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('prompts', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('prompts', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('prompts', 'difficulty')
    op.drop_column('prompts', 'tech_stack')
    op.create_table('tech_stack_prompts',
    sa.Column('tech_prompt_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tech_stack', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'HARD', name='difficulty'), autoincrement=False, nullable=False),
    sa.Column('generated_prompt', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tech_prompt_id', name='tech_stack_prompts_pkey')
    )
    # ### end Alembic commands ###
